import {makeStyles} from '../../styles';
import type {Theme} from '@mui/material/styles';
import {deferredPreviewSectionStyle, generatorFontFamily} from './config';

export const useStyles = makeStyles()((theme: Theme) => ({
  root: {
    minHeight: '100vh',
    backgroundColor: 'var(--color-surface-depth)',
    color: 'var(--color-fg-primary)',
    fontFamily: generatorFontFamily,
    WebkitFontSmoothing: 'antialiased',
    '& input, & button, & textarea, & select, & pre, & code': {
      fontFamily: generatorFontFamily,
    },
  },
  controlBar: {
    position: 'sticky',
    top: 0,
    zIndex: 5,
    display: 'flex',
    justifyContent: 'center',
    borderBottom: '1px solid var(--color-line-base)',
    backgroundColor: 'var(--color-surface-base)',
  },
  controlBarInner: {
    width: '100%',
    maxWidth: 1240,
    minHeight: 64,
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) auto',
    gap: theme.spacing(2),
    alignItems: 'center',
    padding: theme.spacing(0, 3),
    [theme.breakpoints.down('sm')]: {
      gridTemplateColumns: '1fr',
      gap: theme.spacing(1),
      padding: theme.spacing(1, 1.5),
    },
  },
  appTitle: {
    margin: 0,
    color: 'var(--color-fg-primary)',
    fontSize: 16,
    lineHeight: 1.2,
    fontWeight: 800,
    letterSpacing: 0,
  },
  navLink: {
    color: 'var(--color-fg-tertiary)',
    fontSize: 12,
    lineHeight: 1.2,
    fontWeight: 800,
    textDecoration: 'none',
    transition: 'color 160ms ease',
    '&:focus-visible': {
      outline: '2px solid var(--color-line-accent)',
      outlineOffset: 3,
    },
    '@media (hover: hover) and (pointer: fine)': {
      '&:hover': {
        color: 'var(--color-fg-primary)',
      },
    },
  },
  controlCluster: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: theme.spacing(0.75),
    minHeight: 48,
    padding: theme.spacing(0.5),
    border: '1px solid var(--color-line-base)',
    borderRadius: 8,
    backgroundColor: 'var(--color-surface-primary)',
    [theme.breakpoints.down('sm')]: {
      width: '100%',
      justifyContent: 'space-between',
    },
  },
  modeControl: {
    display: 'inline-grid',
    gridTemplateColumns: 'repeat(4, auto)',
    gap: 4,
    minHeight: 44,
    [theme.breakpoints.down('sm')]: {
      gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
      flex: '1 1 auto',
    },
  },
  modeButton: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: theme.spacing(0.65),
    minHeight: 38,
    minWidth: 0,
    padding: theme.spacing(0.55, 1),
    border: '1px solid transparent',
    borderRadius: 6,
    backgroundColor: 'transparent',
    color: 'var(--color-fg-secondary)',
    fontSize: 13,
    fontWeight: 700,
    cursor: 'pointer',
    touchAction: 'manipulation',
    transition:
      'background-color 160ms ease, border-color 160ms ease, color 160ms ease, box-shadow 160ms ease',
    '&:focus-visible': {
      outline: '2px solid var(--color-line-accent)',
      outlineOffset: 2,
    },
    '@media (hover: hover) and (pointer: fine)': {
      '&:hover': {
        backgroundColor: 'var(--color-surface-secondary)',
      },
    },
  },
  modeButtonActive: {
    borderColor: 'var(--color-line-base)',
    backgroundColor: 'var(--color-surface-base)',
    color: 'var(--color-fg-primary)',
  },
  modeIcon: {
    width: 10,
    height: 10,
    flex: '0 0 auto',
    border: '1.5px solid currentColor',
  },
  modeIconCircle: {
    borderRadius: '50%',
  },
  modeIconDiamond: {
    transform: 'rotate(45deg) scale(0.82)',
  },
  modeIconFilled: {
    backgroundColor: 'currentColor',
  },
  settingsDivider: {
    width: 1,
    height: 32,
    backgroundColor: 'var(--color-line-base)',
    [theme.breakpoints.down('sm')]: {
      display: 'none',
    },
  },
  settingsToggle: {
    position: 'relative',
    width: 38,
    height: 38,
    border: '1px solid var(--color-line-base)',
    borderRadius: 6,
    backgroundColor: 'var(--color-surface-base)',
    color: 'var(--color-fg-primary)',
    cursor: 'pointer',
    touchAction: 'manipulation',
    transition:
      'background-color 160ms ease, border-color 160ms ease, box-shadow 160ms ease',
    '&::before': {
      content: '""',
      position: 'absolute',
      inset: 10,
      border: '1.5px solid currentColor',
      borderRadius: '50%',
      opacity: 0.65,
    },
    '&::after': {
      content: '""',
      position: 'absolute',
      inset: 14,
      border: '1px solid currentColor',
      borderRadius: '50%',
      opacity: 0.9,
    },
    '&:focus-visible': {
      outline: '2px solid var(--color-line-accent)',
      outlineOffset: 2,
    },
    '@media (hover: hover) and (pointer: fine)': {
      '&:hover': {
        borderColor: 'var(--color-line-primary)',
        backgroundColor: 'var(--color-surface-secondary)',
      },
    },
  },
  settingsToggleActive: {
    borderColor: 'var(--color-line-primary)',
    backgroundColor: 'var(--color-surface-secondary)',
  },
  seedPopover: {
    position: 'sticky',
    top: 88,
    alignSelf: 'flex-start',
    flex: '0 0 280px',
    maxWidth: '100%',
    minWidth: 0,
    padding: theme.spacing(2),
    border: '1px solid var(--color-line-base)',
    borderRadius: 8,
    backgroundColor: 'var(--color-surface-primary)',
    boxShadow: 'none',
    [theme.breakpoints.down('md')]: {
      position: 'static',
      // Reset the fixed basis so the rail spans full width above the content
      // when the layout stacks.
      flex: '0 0 auto',
      alignSelf: 'stretch',
    },
  },
  seedPopoverHidden: {
    display: 'none',
  },
  seedHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: theme.spacing(1),
    marginBottom: theme.spacing(1.6),
  },
  seedTitle: {
    margin: 0,
    color: 'var(--color-fg-primary)',
    fontSize: 13,
    lineHeight: 1.2,
    fontWeight: 800,
    letterSpacing: 0,
  },
  seedResetButton: {
    minHeight: 36,
    padding: theme.spacing(0.4, 0.6),
    border: 0,
    borderRadius: 6,
    backgroundColor: 'transparent',
    color: 'var(--color-fg-secondary)',
    fontSize: 12,
    fontWeight: 700,
    cursor: 'pointer',
    touchAction: 'manipulation',
    transition: 'background-color 160ms ease, color 160ms ease',
    '&:focus-visible': {
      outline: '2px solid var(--color-line-accent)',
      outlineOffset: 2,
    },
    '@media (hover: hover) and (pointer: fine)': {
      '&:hover': {
        backgroundColor: 'var(--color-surface-secondary)',
        color: 'var(--color-fg-primary)',
      },
    },
  },
  seedField: {
    display: 'grid',
    gap: theme.spacing(0.8),
    marginTop: theme.spacing(1),
  },
  seedFieldLabel: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: theme.spacing(1),
    color: 'var(--color-fg-secondary)',
    fontSize: 11,
    lineHeight: 1.25,
    fontWeight: 700,
  },
  seedValue: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: theme.spacing(0.55),
    color: 'var(--color-fg-tertiary)',
    fontFamily: generatorFontFamily,
    fontVariantNumeric: 'tabular-nums',
  },
  baseSeedRow: {
    display: 'flex',
    alignItems: 'center',
    gap: theme.spacing(1),
  },
  seedColorInput: {
    width: 36,
    height: 36,
    padding: theme.spacing(0.3),
    border: '1px solid var(--color-line-base)',
    borderRadius: 6,
    backgroundColor: 'var(--color-surface-base)',
    cursor: 'pointer',
  },
  seedTextInput: {
    width: '100%',
    minWidth: 0,
    minHeight: 36,
    padding: theme.spacing(0.45, 0.75),
    border: '1px solid var(--color-line-base)',
    borderRadius: 6,
    backgroundColor: 'var(--color-surface-base)',
    color: 'var(--color-fg-primary)',
    fontSize: 12,
    fontWeight: 700,
    outline: 0,
    transition: 'border-color 160ms ease, box-shadow 160ms ease',
    '&:focus': {
      borderColor: 'var(--color-line-accent)',
      boxShadow: '0 0 0 3px var(--color-surface-accent-muted)',
    },
  },
  seedTextInputInvalid: {
    borderColor: 'var(--color-line-destructive)',
    '&:focus': {
      borderColor: 'var(--color-line-destructive)',
      boxShadow: '0 0 0 3px var(--color-surface-destructive-muted)',
    },
  },
  seedHelperText: {
    color: 'var(--color-fg-tertiary)',
    fontSize: 10,
    lineHeight: 1.25,
    fontWeight: 700,
  },
  seedErrorText: {
    color: 'var(--color-fg-destructive)',
  },
  oklchControlGrid: {
    display: 'grid',
    gap: theme.spacing(0.85),
  },
  oklchNumberInput: {
    width: 68,
    minHeight: 30,
    padding: theme.spacing(0.3, 0.5),
    border: '1px solid var(--color-line-base)',
    borderRadius: 6,
    backgroundColor: 'var(--color-surface-base)',
    color: 'var(--color-fg-primary)',
    fontSize: 11,
    fontWeight: 800,
    fontVariantNumeric: 'tabular-nums',
    textAlign: 'right',
    outline: 0,
    '&:focus': {
      borderColor: 'var(--color-line-accent)',
      boxShadow: '0 0 0 3px var(--color-surface-accent-muted)',
    },
  },
  seedSlider: {
    width: '100%',
    minHeight: 28,
    accentColor: 'var(--preview-accent-seed)',
  },
  seedHueDot: {
    width: 14,
    height: 14,
    borderRadius: '50%',
    backgroundColor: 'var(--preview-neutral-seed)',
    boxShadow: 'inset 0 0 0 1px var(--color-line-base)',
  },
  seedSwatchGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: theme.spacing(0.75),
  },
  seedSwatchButton: {
    minWidth: 0,
    padding: 0,
    border: 0,
    backgroundColor: 'transparent',
    color: 'var(--color-fg-tertiary)',
    fontSize: 13,
    lineHeight: 1.2,
    fontWeight: 700,
    textAlign: 'center',
    cursor: 'pointer',
    touchAction: 'manipulation',
    transition: 'color 160ms ease',
    '&:focus-visible': {
      outline: '2px solid var(--color-line-accent)',
      outlineOffset: 2,
    },
    '@media (hover: hover) and (pointer: fine)': {
      '&:hover': {
        color: 'var(--color-fg-primary)',
      },
    },
  },
  seedSwatchButtonActive: {
    color: 'var(--color-fg-primary)',
    [`& .seedSwatchIndicator`]: {
      boxShadow:
        '0 0 0 2px var(--color-line-accent), inset 0 0 0 1px var(--color-line-transparent)',
    },
  },
  seedSwatch: {
    display: 'block',
    width: 28,
    height: 28,
    margin: '0 auto 4px',
    border: '2px solid var(--color-surface-primary)',
    borderRadius: 6,
    backgroundColor: 'var(--preview-accent-seed)',
    boxShadow:
      '0 0 0 1px var(--color-line-base), inset 0 0 0 1px var(--color-line-transparent)',
  },
  shell: {
    width: '100%',
    maxWidth: 1240,
    margin: '0 auto',
    padding: theme.spacing(4, 3, 8),
    // Flexbox (not CSS grid) for the seed-rail / content split: a fixed-width
    // rail + a flexible content pane. This avoids grid auto-placement, which
    // rendered the content overlapping the rail inside the Storybook canvas.
    display: 'flex',
    alignItems: 'flex-start',
    gap: theme.spacing(3),
    [theme.breakpoints.down('md')]: {
      flexDirection: 'column',
      padding: theme.spacing(3, 2, 6),
    },
  },
  contentColumn: {
    flex: '1 1 0%',
    minWidth: 0,
    [theme.breakpoints.down('md')]: {
      alignSelf: 'stretch',
    },
  },
  // When the seed rail is hidden it leaves flex flow entirely, so the content
  // pane fills the row on its own — no explicit span needed (kept as a no-op).
  contentColumnFull: {},
  pageHeader: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr)',
    gap: theme.spacing(1),
    marginBottom: theme.spacing(2.5),
    paddingBottom: theme.spacing(2.5),
    borderBottom: '1px solid var(--color-line-base)',
  },
  pageTitle: {
    margin: 0,
    color: 'var(--color-fg-primary)',
    fontFamily: generatorFontFamily,
    fontSize: 'clamp(34px, 4.4vw, 56px)',
    lineHeight: 1,
    fontWeight: 800,
    letterSpacing: 0,
  },
  pageSubtitle: {
    maxWidth: 560,
    margin: theme.spacing(0.75, 0, 0),
    color: 'var(--color-fg-secondary)',
    fontSize: 15,
    lineHeight: 1.6,
  },
  statusRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: theme.spacing(0.75),
    marginTop: theme.spacing(1.4),
  },
  statusPill: {
    display: 'inline-flex',
    alignItems: 'center',
    minHeight: 28,
    padding: theme.spacing(0.35, 0.75),
    border: '1px solid var(--color-line-base)',
    borderRadius: 6,
    backgroundColor: 'var(--color-surface-secondary)',
    color: 'var(--color-fg-secondary)',
    fontSize: 11,
    lineHeight: 1.2,
    fontWeight: 800,
    fontVariantNumeric: 'tabular-nums',
  },
  diagnosticsGrid: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 0.7fr) minmax(0, 1.3fr)',
    gap: theme.spacing(1.5),
    marginTop: theme.spacing(2),
    [theme.breakpoints.down('md')]: {
      gridTemplateColumns: '1fr',
    },
  },
  diagnosticsCardWide: {
    gridColumn: '1 / -1',
  },
  diagnosticsCard: {
    minWidth: 0,
    padding: theme.spacing(1.5),
    border: '1px solid var(--color-line-base)',
    borderRadius: 8,
    backgroundColor: 'var(--color-surface-base)',
  },
  diagnosticsGridList: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: theme.spacing(0.75),
    marginTop: theme.spacing(1),
  },
  diagnosticsGridListTight: {
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    [theme.breakpoints.down('sm')]: {
      gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    },
  },
  diagnosticMetric: {
    minWidth: 0,
    padding: theme.spacing(0.75),
    border: '1px solid var(--color-line-base)',
    borderRadius: 6,
    backgroundColor: 'var(--color-surface-primary)',
  },
  diagnosticLabel: {
    display: 'block',
    color: 'var(--color-fg-tertiary)',
    fontSize: 10,
    lineHeight: 1.2,
    fontWeight: 800,
  },
  diagnosticValue: {
    display: 'block',
    marginTop: 2,
    color: 'var(--color-fg-primary)',
    fontFamily: generatorFontFamily,
    fontSize: 13,
    lineHeight: 1.25,
    fontWeight: 800,
    fontVariantNumeric: 'tabular-nums',
  },
  referenceTableScroller: {
    overflowX: 'auto',
    marginTop: theme.spacing(1),
    border: '1px solid var(--color-line-base)',
    borderRadius: 8,
  },
  referenceTable: {
    width: '100%',
    minWidth: 620,
    borderCollapse: 'separate',
    borderSpacing: 0,
    tableLayout: 'fixed',
  },
  referenceHeaderCell: {
    height: 32,
    minWidth: 96,
    whiteSpace: 'nowrap',
    padding: theme.spacing(0.45, 0.7),
    borderBottom: '1px solid var(--color-line-base)',
    backgroundColor: 'var(--color-surface-primary)',
    color: 'var(--color-fg-tertiary)',
    fontSize: 10,
    lineHeight: 1.2,
    fontWeight: 800,
    textAlign: 'left',
  },
  referenceCell: {
    height: 32,
    padding: theme.spacing(0.45, 0.7),
    borderBottom: '1px solid var(--color-line-base)',
    color: 'var(--color-fg-secondary)',
    fontFamily: generatorFontFamily,
    fontSize: 10,
    lineHeight: 1.2,
    fontWeight: 800,
    fontVariantNumeric: 'tabular-nums',
    whiteSpace: 'nowrap',
  },
  referenceDeltaPositive: {
    color: 'var(--color-fg-positive)',
  },
  referenceDeltaNegative: {
    color: 'var(--color-fg-destructive)',
  },
  comparisonTableScroller: {
    overflowX: 'auto',
    marginTop: theme.spacing(1.25),
    border: '1px solid var(--color-line-base)',
    borderRadius: 8,
    backgroundColor: 'var(--color-surface-primary)',
  },
  comparisonTable: {
    width: '100%',
    minWidth: 780,
    borderCollapse: 'separate',
    borderSpacing: 0,
    tableLayout: 'fixed',
  },
  comparisonCell: {
    height: 48,
    padding: theme.spacing(0.55, 0.7),
    borderBottom: '1px solid var(--color-line-base)',
    borderLeft: '1px solid var(--color-line-base)',
    color: 'var(--color-fg-secondary)',
    fontFamily: generatorFontFamily,
    fontSize: 10,
    lineHeight: 1.2,
    fontWeight: 800,
    fontVariantNumeric: 'tabular-nums',
    verticalAlign: 'middle',
  },
  comparisonLabelCell: {
    borderLeft: 0,
    color: 'var(--color-fg-primary)',
  },
  comparisonSwatch: {
    width: '100%',
    height: 20,
    marginBottom: 4,
    borderRadius: 4,
    backgroundColor: 'var(--preview-generated-token)',
    boxShadow: 'inset 0 0 0 1px var(--color-line-transparent)',
  },
  debugList: {
    display: 'grid',
    gap: theme.spacing(0.65),
    margin: theme.spacing(1, 0, 0),
    padding: 0,
    listStyle: 'none',
  },
  debugListItem: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: theme.spacing(1),
    minHeight: 30,
    padding: theme.spacing(0.45, 0.65),
    border: '1px solid var(--color-line-base)',
    borderRadius: 6,
    backgroundColor: 'var(--color-surface-primary)',
    color: 'var(--color-fg-secondary)',
    fontSize: 11,
    lineHeight: 1.25,
    fontWeight: 800,
  },
  debugValue: {
    color: 'var(--color-fg-primary)',
    fontVariantNumeric: 'tabular-nums',
  },
  apcaTableScroller: {
    overflowX: 'auto',
    marginTop: theme.spacing(2),
    border: '1px solid var(--color-line-base)',
    borderRadius: 8,
  },
  apcaTable: {
    width: '100%',
    minWidth: 720,
    borderCollapse: 'separate',
    borderSpacing: 0,
    tableLayout: 'fixed',
  },
  apcaBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    minHeight: 22,
    padding: theme.spacing(0.25, 0.55),
    border: '1px solid var(--color-line-base)',
    borderRadius: 5,
    backgroundColor: 'var(--color-surface-primary)',
    color: 'var(--color-fg-secondary)',
    fontSize: 10,
    lineHeight: 1,
    fontWeight: 900,
  },
  apcaBadgePass: {
    borderColor: 'var(--color-line-positive)',
    color: 'var(--color-fg-positive)',
  },
  apcaBadgeWarn: {
    borderColor: 'var(--color-line-attention)',
    color: 'var(--color-fg-attention)',
  },
  primitiveCard: {
    ...deferredPreviewSectionStyle,
    marginTop: theme.spacing(2),
    padding: theme.spacing(2),
    border: '1px solid var(--color-line-base)',
    borderRadius: 8,
    backgroundColor: 'var(--color-surface-base)',
  },
  primitiveCardHeader: {
    display: 'flex',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: theme.spacing(1.5),
    marginBottom: theme.spacing(1.5),
    [theme.breakpoints.down('sm')]: {
      alignItems: 'flex-start',
      flexDirection: 'column',
    },
  },
  primitiveTitle: {
    margin: 0,
    color: 'var(--color-fg-primary)',
    fontSize: 15,
    lineHeight: 1.2,
    fontWeight: 800,
    letterSpacing: 0,
  },
  primitiveDescription: {
    maxWidth: 700,
    margin: theme.spacing(0.45, 0, 0),
    color: 'var(--color-fg-secondary)',
    fontSize: 13,
    lineHeight: 1.45,
  },
  primitiveMeta: {
    display: 'inline-flex',
    gap: theme.spacing(0.65),
    flexWrap: 'wrap',
  },
  primitiveMetaPill: {
    display: 'inline-flex',
    alignItems: 'center',
    minHeight: 26,
    padding: theme.spacing(0.3, 0.65),
    border: '1px solid var(--color-line-base)',
    borderRadius: 6,
    backgroundColor: 'var(--color-surface-secondary)',
    color: 'var(--color-fg-tertiary)',
    fontSize: 11,
    lineHeight: 1.2,
    fontWeight: 800,
    fontVariantNumeric: 'tabular-nums',
  },
  primitiveTableScroller: {
    overflowX: 'auto',
    border: '1px solid var(--color-line-base)',
    borderRadius: 8,
    backgroundColor: 'var(--color-surface-primary)',
  },
  primitiveTable: {
    width: '100%',
    minWidth: 980,
    borderCollapse: 'separate',
    borderSpacing: 0,
    // `auto` (not `fixed`) so per-cell min-widths set a healthy column floor and
    // the table scrolls horizontally instead of squishing all 18 shade columns.
    tableLayout: 'auto',
  },
  primitiveHeaderCell: {
    height: 34,
    minWidth: 64,
    whiteSpace: 'nowrap',
    padding: theme.spacing(0.55, 0.7),
    borderBottom: '1px solid var(--color-line-base)',
    color: 'var(--color-fg-tertiary)',
    fontFamily: generatorFontFamily,
    fontSize: 11,
    lineHeight: 1.2,
    fontWeight: 800,
    fontVariantNumeric: 'tabular-nums',
    textAlign: 'center',
  },
  primitiveFamilyCell: {
    width: 112,
    padding: theme.spacing(0.75),
    borderBottom: '1px solid var(--color-line-base)',
    color: 'var(--color-fg-secondary)',
    fontSize: 12,
    lineHeight: 1.2,
    fontWeight: 800,
    textAlign: 'left',
    verticalAlign: 'middle',
  },
  primitiveShadeCell: {
    height: 64,
    minWidth: 68,
    padding: 0,
    borderBottom: '1px solid var(--color-line-base)',
    borderLeft: '1px solid var(--color-line-base)',
  },
  primitiveShadeButton: {
    width: '100%',
    height: 64,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: theme.spacing(0.35),
    padding: theme.spacing(0.7),
    border: 0,
    backgroundColor: 'var(--preview-primitive-color-srgb)',
    color: 'var(--color-fg-primary)',
    cursor: 'copy',
    touchAction: 'manipulation',
    boxShadow: 'inset 0 0 0 1px var(--color-line-transparent)',
    transition: 'box-shadow 160ms ease, transform 160ms ease',
    '@supports (color: oklch(0.5 0.1 40))': {
      backgroundColor: 'var(--preview-primitive-color-p3)',
    },
    '&:focus-visible': {
      outline: '2px solid var(--color-line-accent)',
      outlineOffset: -2,
    },
    '@media (hover: hover) and (pointer: fine)': {
      '&:hover': {
        boxShadow:
          'inset 0 0 0 1px var(--color-line-primary), var(--color-shadow-surface-xxs)',
        transform: 'translateY(-1px)',
      },
    },
  },
  primitiveShadeBadge: {
    maxWidth: '100%',
    padding: theme.spacing(0.2, 0.4),
    border: '1px solid var(--color-line-transparent)',
    borderRadius: 4,
    backgroundColor: 'var(--color-surface-base)',
    color: 'var(--color-fg-secondary)',
    fontFamily: generatorFontFamily,
    fontSize: 10,
    lineHeight: 1.15,
    fontWeight: 800,
    fontVariantNumeric: 'tabular-nums',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  semanticCard: {
    ...deferredPreviewSectionStyle,
    marginTop: theme.spacing(2),
    padding: theme.spacing(2.5),
    border: '1px solid var(--color-line-base)',
    borderRadius: 8,
    backgroundColor: 'var(--color-surface-base)',
  },
  recipeCard: {
    ...deferredPreviewSectionStyle,
    marginTop: theme.spacing(2),
    padding: theme.spacing(2),
    borderRadius: 8,
    backgroundColor: 'var(--color-surface-base)',
    boxShadow: 'var(--color-shadow-surface-xs)',
  },
  recipeGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: theme.spacing(1),
    marginTop: theme.spacing(1.5),
    [theme.breakpoints.down('md')]: {
      gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    },
    [theme.breakpoints.down('sm')]: {
      gridTemplateColumns: '1fr',
    },
  },
  recipeItem: {
    minWidth: 0,
    padding: theme.spacing(1),
    borderRadius: 8,
    backgroundColor: 'var(--color-surface-primary)',
    boxShadow: 'var(--color-shadow-surface-xxs)',
  },
  recipePreview: {
    minHeight: 56,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: theme.spacing(0.75, 1),
    borderRadius: 6,
    backgroundColor: 'var(--preview-recipe-bg)',
    color: 'var(--preview-recipe-fg)',
    boxShadow:
      'var(--preview-recipe-shadow), inset 0 0 0 1px var(--preview-recipe-line)',
    fontSize: 12,
    lineHeight: 1.2,
    fontWeight: 800,
  },
  recipeName: {
    display: 'block',
    marginTop: theme.spacing(0.75),
    color: 'var(--color-fg-secondary)',
    fontFamily: generatorFontFamily,
    fontSize: 12,
    lineHeight: 1.25,
    fontWeight: 800,
  },
  recipeSlotGrid: {
    display: 'grid',
    gap: theme.spacing(0.35),
    marginTop: theme.spacing(0.75),
  },
  recipeSlot: {
    minWidth: 0,
    display: 'grid',
    gridTemplateColumns: '48px minmax(0, 1fr)',
    gap: theme.spacing(0.55),
    color: 'var(--color-fg-tertiary)',
    fontFamily: generatorFontFamily,
    fontSize: 10,
    lineHeight: 1.2,
    fontWeight: 800,
  },
  recipeToken: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    color: 'var(--color-fg-secondary)',
  },
  alphaMatrix: {
    overflowX: 'auto',
    marginTop: theme.spacing(2),
    border: '1px solid var(--color-line-base)',
    borderRadius: 8,
    backgroundColor: 'var(--color-surface-primary)',
  },
  alphaTable: {
    width: '100%',
    minWidth: 920,
    borderCollapse: 'separate',
    borderSpacing: 0,
    // `auto` so each surface column keeps a readable min-width and the table
    // scrolls rather than the columns sprawling or squishing to fill the pane.
    tableLayout: 'auto',
  },
  alphaCell: {
    height: 58,
    minWidth: 104,
    padding: theme.spacing(0.45),
    borderBottom: '1px solid var(--color-line-base)',
    borderLeft: '1px solid var(--color-line-base)',
    backgroundColor: 'var(--preview-alpha-bg)',
  },
  alphaSwatch: {
    width: '100%',
    height: 38,
    borderRadius: 6,
    backgroundColor: 'var(--preview-alpha-fill)',
    boxShadow: 'inset 0 0 0 1px var(--color-line-transparent)',
  },
  outputToolbar: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: theme.spacing(1),
    marginTop: theme.spacing(1.5),
  },
  outputModeGroup: {
    display: 'inline-grid',
    gridTemplateColumns: 'repeat(4, minmax(0, auto))',
    gap: 4,
    padding: 4,
    border: '1px solid var(--color-line-base)',
    borderRadius: 8,
    backgroundColor: 'var(--color-surface-primary)',
    [theme.breakpoints.down('sm')]: {
      width: '100%',
      gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    },
  },
  outputButton: {
    minHeight: 34,
    padding: theme.spacing(0.45, 0.75),
    border: '1px solid transparent',
    borderRadius: 6,
    backgroundColor: 'transparent',
    color: 'var(--color-fg-secondary)',
    fontSize: 11,
    lineHeight: 1.2,
    fontWeight: 900,
    cursor: 'pointer',
    touchAction: 'manipulation',
    '&:focus-visible': {
      outline: '2px solid var(--color-line-accent)',
      outlineOffset: 2,
    },
  },
  outputButtonActive: {
    borderColor: 'var(--color-line-base)',
    backgroundColor: 'var(--color-surface-base)',
    color: 'var(--color-fg-primary)',
  },
  outputActionGroup: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: theme.spacing(0.75),
  },
  outputActionButton: {
    minHeight: 34,
    padding: theme.spacing(0.45, 0.75),
    border: '1px solid var(--color-line-base)',
    borderRadius: 6,
    backgroundColor: 'var(--color-surface-primary)',
    color: 'var(--color-fg-secondary)',
    fontSize: 11,
    lineHeight: 1.2,
    fontWeight: 900,
    cursor: 'pointer',
    touchAction: 'manipulation',
    '&:focus-visible': {
      outline: '2px solid var(--color-line-accent)',
      outlineOffset: 2,
    },
  },
  tokenGroup: {
    marginTop: theme.spacing(3.2),
    '&:first-of-type': {
      marginTop: 0,
    },
  },
  groupLabel: {
    margin: theme.spacing(0, 0, 1),
    color: 'var(--color-fg-tertiary)',
    fontSize: 12,
    lineHeight: 1.3,
    fontWeight: 800,
    letterSpacing: 0,
  },
  tokenSwatchGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    gap: theme.spacing(1),
    [theme.breakpoints.down('md')]: {
      gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    },
    [theme.breakpoints.down('sm')]: {
      gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    },
  },
  tokenSwatchItem: {
    minWidth: 0,
    minHeight: 130,
    padding: theme.spacing(0.85),
    border: '1px solid var(--color-line-base)',
    borderRadius: 8,
    backgroundColor: 'var(--color-surface-primary)',
  },
  tokenSwatchButton: {
    width: '100%',
    minHeight: 72,
    padding: 0,
    border: 0,
    borderRadius: 6,
    backgroundColor: 'var(--preview-generated-token)',
    backgroundImage:
      'linear-gradient(var(--preview-generated-token), var(--preview-generated-token)), var(--preview-token-checker)',
    backgroundPosition: '0 0, 0 0, 0 9px, 9px -9px, -9px 0',
    backgroundSize: 'auto, 18px 18px, 18px 18px, 18px 18px, 18px 18px',
    cursor: 'copy',
    touchAction: 'manipulation',
    boxShadow: 'inset 0 0 0 1px var(--color-line-transparent)',
    transition: 'box-shadow 160ms ease, transform 160ms ease',
    '&:focus-visible': {
      outline: '2px solid var(--color-line-accent)',
      outlineOffset: 2,
    },
    '@media (hover: hover) and (pointer: fine)': {
      '&:hover': {
        boxShadow:
          'inset 0 0 0 1px var(--color-line-primary), var(--color-shadow-surface-xxs)',
        transform: 'translateY(-1px)',
      },
    },
  },
  tokenSwatchLabel: {
    display: 'block',
    marginTop: theme.spacing(0.45),
    color: 'var(--color-fg-secondary)',
    fontFamily: generatorFontFamily,
    fontSize: 12,
    lineHeight: 1.25,
    fontWeight: 800,
    wordBreak: 'break-word',
  },
  tokenContrastLabel: {
    display: 'block',
    marginTop: 2,
    color: 'var(--color-fg-tertiary)',
    fontFamily: generatorFontFamily,
    fontSize: 10,
    lineHeight: 1.25,
    fontWeight: 800,
    fontVariantNumeric: 'tabular-nums',
    wordBreak: 'break-word',
  },
  tokenQualityRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 4,
    marginTop: theme.spacing(0.45),
  },
  tokenQualityBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    minHeight: 18,
    padding: theme.spacing(0.15, 0.35),
    border: '1px solid var(--color-line-base)',
    borderRadius: 4,
    backgroundColor: 'var(--color-surface-base)',
    color: 'var(--color-fg-tertiary)',
    fontSize: 9,
    lineHeight: 1,
    fontWeight: 900,
    fontVariantNumeric: 'tabular-nums',
  },
  tokenQualityBadgePass: {
    borderColor: 'var(--color-line-positive)',
    color: 'var(--color-fg-positive)',
  },
  tokenQualityBadgeWarn: {
    borderColor: 'var(--color-line-attention)',
    color: 'var(--color-fg-attention)',
  },
  section: {
    ...deferredPreviewSectionStyle,
    marginTop: theme.spacing(7),
  },
  sectionTitle: {
    margin: 0,
    color: 'var(--color-fg-primary)',
    fontFamily: generatorFontFamily,
    fontSize: 30,
    lineHeight: 1.1,
    fontWeight: 800,
    letterSpacing: 0,
  },
  sectionDescription: {
    maxWidth: 760,
    margin: theme.spacing(0.65, 0, 0),
    color: 'var(--color-fg-secondary)',
    fontSize: 14,
    lineHeight: 1.5,
  },
  hierarchyCard: {
    marginTop: theme.spacing(2),
    padding: theme.spacing(2.5),
    border: '1px solid var(--color-line-base)',
    borderRadius: 8,
    backgroundColor: 'var(--color-surface-base)',
  },
  surfaceNest: {
    minHeight: 48,
    padding: theme.spacing(1.5),
    border: '1px solid var(--preview-generated-line)',
    borderRadius: 8,
    backgroundColor: 'var(--preview-generated-token)',
  },
  surfaceNestRoot: {
    minHeight: 320,
  },
  surfaceNestInner: {
    marginTop: theme.spacing(1.3),
  },
  surfaceNestLabel: {
    color: 'var(--color-fg-tertiary)',
    fontFamily: generatorFontFamily,
    fontSize: 12,
    lineHeight: 1.3,
    fontWeight: 800,
  },
  shadowCard: {
    marginTop: theme.spacing(1.5),
    padding: theme.spacing(2.5),
    border: '1px solid var(--color-line-base)',
    borderRadius: 8,
    backgroundColor: 'var(--color-surface-primary)',
  },
  shadowGrid: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: theme.spacing(1.5),
    marginTop: theme.spacing(1.5),
  },
  shadowBox: {
    width: 58,
    height: 58,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: 0,
    borderRadius: 6,
    backgroundColor: 'var(--color-surface-secondary)',
    color: 'var(--color-fg-tertiary)',
    boxShadow: 'var(--preview-generated-effect)',
    fontSize: 12,
    fontWeight: 800,
  },
  effectCatalog: {
    marginTop: theme.spacing(1.5),
    padding: theme.spacing(2.5),
    border: '1px solid var(--color-line-base)',
    borderRadius: 8,
    backgroundColor: 'var(--color-surface-base)',
  },
  effectGroup: {
    marginTop: theme.spacing(2.4),
    '&:first-of-type': {
      marginTop: 0,
    },
  },
  effectPreviewGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(6, minmax(0, 1fr))',
    gap: theme.spacing(1),
    marginTop: theme.spacing(1),
    [theme.breakpoints.down('md')]: {
      gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    },
    [theme.breakpoints.down('sm')]: {
      gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    },
  },
  effectPreviewItem: {
    minWidth: 0,
  },
  effectPreviewBox: {
    width: '100%',
    height: 58,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: 0,
    borderRadius: 6,
    backgroundColor: 'var(--color-surface-primary)',
    color: 'var(--color-fg-tertiary)',
    boxShadow: 'var(--preview-generated-effect)',
    fontSize: 11,
    fontWeight: 800,
  },
  effectPreviewBoxGlow: {
    backgroundColor: 'var(--color-surface-primary)',
    boxShadow:
      'inset 0 0 0 1px var(--color-line-base), 0 0 0 10px var(--preview-generated-effect)',
  },
  effectPreviewBoxGradient: {
    backgroundImage:
      'var(--preview-generated-effect), linear-gradient(var(--color-surface-primary), var(--color-surface-primary))',
    boxShadow: 'inset 0 0 0 1px var(--color-line-base)',
  },
  effectPreviewLabel: {
    display: 'block',
    marginTop: theme.spacing(0.45),
    color: 'var(--color-fg-tertiary)',
    fontFamily: generatorFontFamily,
    fontSize: 10,
    lineHeight: 1.25,
    fontWeight: 800,
    wordBreak: 'break-word',
  },
  effectLayerList: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 4,
    marginTop: theme.spacing(0.45),
  },
  effectLayerBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    minHeight: 18,
    padding: theme.spacing(0.15, 0.35),
    border: '1px solid var(--color-line-base)',
    borderRadius: 4,
    color: 'var(--color-fg-tertiary)',
    fontSize: 9,
    lineHeight: 1,
    fontWeight: 900,
  },
  foregroundCard: {
    marginTop: theme.spacing(2),
    padding: theme.spacing(0.85),
    border: '1px solid var(--color-line-base)',
    borderRadius: 8,
    backgroundColor: 'var(--color-surface-base)',
  },
  fgRow: {
    display: 'grid',
    gridTemplateColumns: '120px minmax(0, 1fr) auto',
    gap: theme.spacing(1.5),
    alignItems: 'center',
    minHeight: 52,
    padding: theme.spacing(0.75, 1),
    border: '1px solid var(--color-line-transparent)',
    borderRadius: 6,
    backgroundColor:
      'var(--preview-foreground-surface, var(--color-surface-base))',
    color: 'var(--preview-generated-token)',
    [theme.breakpoints.down('sm')]: {
      gridTemplateColumns: '1fr',
      gap: theme.spacing(0.35),
      padding: theme.spacing(0.4, 0),
    },
  },
  fgTokenLabel: {
    color: 'currentColor',
    fontFamily: generatorFontFamily,
    fontSize: 12,
    lineHeight: 1.3,
    fontWeight: 800,
    opacity: 0.68,
  },
  fgSample: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: theme.spacing(0.65),
    minWidth: 0,
    fontSize: 14,
    lineHeight: 1.45,
    fontWeight: 800,
  },
  fgSampleIcon: {
    width: 12,
    height: 12,
    border: '2px solid currentColor',
    transform: 'rotate(45deg) scale(0.82)',
  },
  fgContrast: {
    color: 'currentColor',
    fontFamily: generatorFontFamily,
    fontSize: 11,
    fontWeight: 800,
    fontVariantNumeric: 'tabular-nums',
    opacity: 0.72,
    [theme.breakpoints.down('sm')]: {
      justifySelf: 'start',
    },
  },
  fgDivider: {
    height: 1,
    margin: theme.spacing(1, 0),
    backgroundColor: 'var(--color-line-base)',
  },
  outputGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: theme.spacing(1.5),
    marginTop: theme.spacing(1.5),
    [theme.breakpoints.down('md')]: {
      gridTemplateColumns: '1fr',
    },
  },
  outputComparisonGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    gap: theme.spacing(1),
    marginTop: theme.spacing(1.5),
    [theme.breakpoints.down('md')]: {
      gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    },
    [theme.breakpoints.down('sm')]: {
      gridTemplateColumns: '1fr',
    },
  },
  outputModeCard: {
    minWidth: 0,
    padding: theme.spacing(1),
    border: '1px solid var(--color-line-base)',
    borderRadius: 8,
    backgroundColor: 'var(--color-surface-primary)',
  },
  outputModeTitle: {
    display: 'block',
    marginBottom: theme.spacing(0.65),
    color: 'var(--color-fg-primary)',
    fontSize: 11,
    lineHeight: 1.2,
    fontWeight: 900,
  },
  codeBlock: {
    minHeight: 180,
    margin: 0,
    padding: theme.spacing(1.25),
    border: '1px solid var(--color-line-base)',
    borderRadius: 8,
    backgroundColor: 'var(--color-surface-depth)',
    color: 'var(--color-fg-secondary)',
    fontFamily: generatorFontFamily,
    fontSize: 11,
    lineHeight: 1.55,
    overflow: 'auto',
  },
  codeBlockCompact: {
    minHeight: 128,
    maxHeight: 280,
  },
}));

export type SandboxClasses = ReturnType<typeof useStyles>['classes'];
export type SandboxCx = (
  ...classNames: Array<string | false | null | undefined>
) => string;
